name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  get_asdf_version:
    runs-on: ubuntu-22.04
    outputs:
      asdf_version: ${{ steps.asdf-version.outputs.version }}
      tag_format: ${{ steps.load-config.outputs.TAG_FORMAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get asdf version
        id: asdf-version
        run: echo "version=$(awk '!/^#/ && NF {print $1; exit}' .tool-versions.asdf)" >> "$GITHUB_OUTPUT"
      - name: Load config value
        id: load-config
        run: |
          TAG_FORMAT=$(yq '.TAG_FORMAT' .github/config/settings.yml)
          echo "TAG_FORMAT=$TAG_FORMAT" >> "$GITHUB_OUTPUT"

  pr_title_format_check:
    uses: NHSDigital/eps-workflow-semantic-release/.github/workflows/pr_title_check.yml@275a3e7bc3efa0db1097c10225f8ee1cfbf5282f
  quality_checks:
    needs: [get_asdf_version]
    uses: NHSDigital/eps-workflow-quality-checks/.github/workflows/quality-checks.yml@4a6d03ad51516eddc448daf454805f85fe2025b9
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.asdf_version }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependabot-auto-approve-and-merge:
    uses: ./.github/workflows/dependabot-auto-approve-and-merge.yml
    secrets:
      AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
      AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}
