name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pr_title_format_check:
    uses: NHSDigital/eps-workflow-semantic-release/.github/workflows/pr_title_check.yml@326225b83f732d4edc4d6628453924d14f11ed90

  dependabot-auto-approve-and-merge:
    uses: ./.github/workflows/dependabot-auto-approve-and-merge.yml
    secrets:
      AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
      AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}
