name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pr_title_format_check:
    uses: NHSDigital/eps-workflow-semantic-release/.github/workflows/pr_title_check.yml@2a3f4ab96e04b7547c4ee5b786745b98809c89be

  dependabot-auto-approve-and-merge:
    uses: ./.github/workflows/dependabot-auto-approve-and-merge.yml
    secrets:
      AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
      AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}
