name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pr_title_format_check:
    uses: NHSDigital/eps-workflow-semantic-release/.github/workflows/pr_title_check.yml@13024fccca97e125d448ca9bc4616cfd413197fe

  dependabot-auto-approve-and-merge:
    uses: ./.github/workflows/dependabot-auto-approve-and-merge.yml
    secrets:
      AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
      AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}
