name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pr_title_format_check:
    uses: NHSDigital/eps-workflow-semantic-release/.github/workflows/pr_title_check.yml@275a3e7bc3efa0db1097c10225f8ee1cfbf5282f

  dependabot-auto-approve-and-merge:
    uses: ./.github/workflows/dependabot-auto-approve-and-merge.yml
    secrets:
      AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
      AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}
